name: Docker Build with Random Data

on:
  push:
    branches: [ main ]

jobs:
  build-and-run-random-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image with Random Data
      run: docker build --tag cohortingtool/webapp:random --build-arg random=true .

    - name: Run Docker Container
      run: docker run --name cogstackcohort-random -d -p 3000:3000 cohortingtool/webapp:random
