name: Docker Build with Real Data

on:
  push:
    branches: [ main ]

jobs:
  build-and-run-real-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image with Real Data
      run: docker build --tag cohortingtool/webapp .

    - name: Run Docker Container
      run: docker run --name cogstackcohort -d -p 3000:3000 cohortingtool/webapp

